#!/usr/bin/env python
import random, sys, getopt

def generar_puertas(cant, vacias):
    puertas = []
    for x in range(cant):
        puerta = random.sample(vacias,1)[0]
        vacias.remove(puerta)
        llave = random.sample(vacias,1)[0]
        vacias.remove(llave)
        puertas.append((llave,puerta))
    return puertas
#!/usr/bin/python

def conectar_nodos(size, conexo, luck, trivial):
    nodos = {}
    for x in range(size):
        actual = x+1
        nodos[actual] = []
        if conexo and actual < size:
            nodos[x+1].append((actual)%size + 1)
        if not trivial and actual == 1:
            tope = size - 1
        else:
            tope = size
        for y in range(actual,tope):
            r = random.randint(0,99)
            if not y+1 in nodos[actual] and r < luck:
                nodos[actual]+=[y+1]
    return nodos

def printGraph(nodos, puertas):
    res = []
    for x in puertas:
        res.append(" "*2 + str(x[0]) + " " + str(x[1]))
    for x in nodos:
        for y in nodos[x]:
            #pongo un poco de ruido
            if y%2 == 2:
                res.append(" "*4 + str(y) + " " + str(x))
            else :
                res.append(" "*4 + str(x) + " " + str(y))
    p = len(puertas)
    m = 0
    for x in nodos:
        m += len(nodos[x])
    n = len(nodos.keys())
    res.insert(0, str(n) + " " + str(p) + " " + str(m))
    print '\n'.join(res)

def main(size, amount = 1, luck = 50, conexo = False, dungeon = False,\
         escalera = False, trivial = False):
    if escalera:
        primero = 20
    else:
        primero = size
    for n in range(primero, size+1):
        for veces in range(amount):
            res = []
            m = 0
            p = 0
            #en cada cuarto solo hay o una puerta o una llave
            #la puerta y la salida no tienen puertas
            #cantidad de puertas maximas: (n - 2)/2
            if dungeon:
                total_puertas = n/2 - 1
            else:
                total_puertas = random.randint(0,n/2 - 1)    
            vacias  = set(range(2,n)) #no incluyo entrada y salida
            puertas = generar_puertas(total_puertas, vacias)
            nodos   = conectar_nodos(n, conexo, luck, trivial)
            printGraph(nodos, puertas)
        
    print "-1 -1 -1"   
    return 0

## entradao
##        |\
##        | \
##        |  \
## llave1 o---o puerta1
##        |\ /|
##        | x |
##        |/ \|
## llave2 o---o puerta2
##        |\ /|
##        
##        .....
##        
##        |/ \|
##        o---o
##        |\ /|
##        | x |
##        |/ \|
## llave no---o puerta n
##            |
##            o salida

def peor(size, escalera=False):
    if escalera:
        primero = 4
    else:
        primero = size
    for veces in range(amount):
        for n in range(primero, size + 1):
            entrada = 1
            salida = n
            total_puertas = (n - 2)/2
            nodos = {}
            puertas = []
            anterior_puerta = entrada
            anterior_llave = entrada
            for x in range(n):
                nodos[x+1] = []
            for x in range(total_puertas):
                llave = x + 2
                puerta = llave + total_puertas
                #conecto diagonal (excepto la primera vez)
                if anterior_puerta != 1:
                    nodos[anterior_puerta] += [llave]
                    nodos[anterior_llave] += [puerta]
                #conecto las verticales
                nodos[anterior_puerta] += [puerta]
                nodos[anterior_llave] += [llave]
                nodos[anterior_puerta].sort(reverse=True)
                #conecto horizontal
                nodos[llave] += [puerta]
                puertas.append((llave, puerta))
                anterior_puerta = puerta
                anterior_llave = llave
            if n%2:
                nodos[n-2] += [n-1]
            nodos[n-1] += [n]
            printGraph(nodos, puertas)
    print " -1"*3
                
                


def usage():
    print ' '.join(sys.argv)
    print "esta mal, se espera:"
    print "./generador [parametros]"
    print "-n --nodos   : numero > 3 (cantidad maxima de nodos)"
    print "-v --veces   : cantidad de grafos con n nodos"
    print "-s --suerte  : densidad del grafo. numero entre 1 y 100"
    print "-c --conexo  : conexo, por default no es conexo"
    print "-d --dungeon : LLENAR DE PUERTAS"
    print "-e --escalera: generar de 4 a n"
    print "-t --trivial : si el primero puede estar conectado con el ultimo"
    print "-p --peor : genera el peor caso"
    print "example: ./generador -n 20 -de -s 25"
    sys.exit(1)

if __name__ == "__main__":

    try:
        opts, args = getopt.getopt(sys.argv[1:], "n:v:s:h:cdetp", ["nodos=", \
            "veces=", "suerte=", "conexo", "dungeon", "escalera", "trivial",\
            "help", "peor"])
    except getopt.GetoptError:
        # print help information and exit:
        print "Error parseando"
        usage()
        sys.exit(2)
    verbose = False
    n = 6
    amount = 1
    luck = 50
    conexo = False
    dungeon = True
    escalera = False
    trivial = False
    for o, a in opts:
        if o == "-v":
            verbose = True
        if o in ("-h", "--help"):
            usage()
        if o in ("-n", "--nodos"):
            try:
                n = int(a)
            except:
                print "se espera numero"
                usage()
        if o in ("-v", "--veces"):
            try:
                amount = int(a)
            except:
                print "se espera numero"
                usage()
        if o in ("-s", "--suerte"):
            try:
                luck = int(a)
            except:
                print "se espera numero"
                usage()
        if o in ("-c", "--conexo"):
            conexo = True
        if o in ("-d", "--dungeon"):
            dungeon = True
        if o in ("-e", "--escalera"):
            escalera = True
        if o in ("-t", "--trivial"):
            trivial = True
        if o in ("-p", "--peor"):
            sys.exit(peor(n, escalera))
    sys.exit(main(n, amount, luck, conexo, dungeon, escalera, trivial))
